/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

/**
 *
 * @author user
 */
public class ReportForm extends javax.swing.JFrame {

    /**
     * Creates new form ReportForm
     */
    public ReportForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bestInCustomersBTN = new javax.swing.JButton();
        viewCustomersBTN = new javax.swing.JButton();
        allCustomerDetailsBTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        itemsSortQtyBTN = new javax.swing.JButton();
        itemsSrtAmountBTN = new javax.swing.JButton();
        viewCustomersBTN2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bestInCustomersBTN2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("View Reports");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Customer Reports");

        bestInCustomersBTN.setBackground(new java.awt.Color(137, 207, 240));
        bestInCustomersBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bestInCustomersBTN.setText("Best In Customers");
        bestInCustomersBTN.setBorder(null);
        bestInCustomersBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestInCustomersBTNActionPerformed(evt);
            }
        });

        viewCustomersBTN.setBackground(new java.awt.Color(137, 207, 240));
        viewCustomersBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewCustomersBTN.setText("View Customers");
        viewCustomersBTN.setBorder(null);
        viewCustomersBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCustomersBTNActionPerformed(evt);
            }
        });

        allCustomerDetailsBTN.setBackground(new java.awt.Color(137, 207, 240));
        allCustomerDetailsBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        allCustomerDetailsBTN.setText("All Customers Details");
        allCustomerDetailsBTN.setBorder(null);
        allCustomerDetailsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allCustomerDetailsBTNActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Item Reports");

        itemsSortQtyBTN.setBackground(new java.awt.Color(177, 221, 99));
        itemsSortQtyBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemsSortQtyBTN.setText("Items srt by QTY");
        itemsSortQtyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemsSortQtyBTNActionPerformed(evt);
            }
        });

        itemsSrtAmountBTN.setBackground(new java.awt.Color(177, 221, 99));
        itemsSrtAmountBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemsSrtAmountBTN.setText("Items srt by amount");
        itemsSrtAmountBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemsSrtAmountBTNActionPerformed(evt);
            }
        });

        viewCustomersBTN2.setBackground(new java.awt.Color(224, 194, 101));
        viewCustomersBTN2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewCustomersBTN2.setText("Orders by amount");
        viewCustomersBTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCustomersBTN2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Order Reports");

        bestInCustomersBTN2.setBackground(new java.awt.Color(224, 194, 101));
        bestInCustomersBTN2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bestInCustomersBTN2.setText("All Orders");
        bestInCustomersBTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestInCustomersBTN2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(allCustomerDetailsBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(viewCustomersBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bestInCustomersBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(itemsSrtAmountBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(itemsSortQtyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(viewCustomersBTN2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bestInCustomersBTN2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(bestInCustomersBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(viewCustomersBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(allCustomerDetailsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(bestInCustomersBTN2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(viewCustomersBTN2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(itemsSortQtyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(itemsSrtAmountBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(72, 72, 72)))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void allCustomerDetailsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allCustomerDetailsBTNActionPerformed
        new AllCustomerDetailsForm().setVisible(true);
    }//GEN-LAST:event_allCustomerDetailsBTNActionPerformed

    private void bestInCustomersBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestInCustomersBTNActionPerformed
        new BestInCustomers().setVisible(true);
        dispose();
    }//GEN-LAST:event_bestInCustomersBTNActionPerformed

    private void viewCustomersBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCustomersBTNActionPerformed
        new  ViewCustomers().setVisible(true);
        dispose();
    }//GEN-LAST:event_viewCustomersBTNActionPerformed

    private void itemsSortQtyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemsSortQtyBTNActionPerformed
        new ItemsByQtyForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_itemsSortQtyBTNActionPerformed

    private void itemsSrtAmountBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemsSrtAmountBTNActionPerformed
        new ItemsByAmount().setVisible(true);
        dispose();
    }//GEN-LAST:event_itemsSrtAmountBTNActionPerformed

    private void bestInCustomersBTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestInCustomersBTN2ActionPerformed
        new AllOrdersForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_bestInCustomersBTN2ActionPerformed

    private void viewCustomersBTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCustomersBTN2ActionPerformed
        new AllOrdersByAmountForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_viewCustomersBTN2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allCustomerDetailsBTN;
    private javax.swing.JButton bestInCustomersBTN;
    private javax.swing.JButton bestInCustomersBTN2;
    private javax.swing.JButton itemsSortQtyBTN;
    private javax.swing.JButton itemsSrtAmountBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton viewCustomersBTN;
    private javax.swing.JButton viewCustomersBTN2;
    // End of variables declaration//GEN-END:variables
}
